class Clase {
	constructor(clase) {
		this._nombre = clase.nombre;
		this._claves = clase.claves;
		this._armadura = clase.armadura;
		this._escudo = clase.escudo;
		this._armas = clase.armas;
		this._equipo = clase.equipo;
		this._competencias = clase.competencias;
		this._talentos = clase.talentos;
		this._ltalentos = clase.ltalentos;
		this._salvacion = clase.salvacion;
		this._pg = clase.pg;
		this._cita = clase.cita;
		this._descripcion = clase.descripcion;
		this._trucos = clase.trucos;
		this._conjuros = clase.conjuros;
	}
}

class Clases {
	
	constructor() {
		this._clases =
		[
			{
			  nombre : "Adalid",
			  claves : [ "[Bueno]", "[Luchador]" ],
			  armadura : "Cota de escamas",
              escudo : "Escudo mediano",
			  armas : [ [ "Espada larga" ] ],
			  equipo: [ "Manta", "Mochila", "Odre" ],
			  competencias: [ "Armaduras ligeras, medianas, pesadas y escudos", 
                              "Armas simples y marciales, tanto cuerpo a cuerpo como a distancia" ],
			  talentos: [ "<strong>Salvación</strong><br/>Si has logrado golpear a un enemigo en tu último turno y este ataca a un aliado que está a menos de 2 metros de tí puedes interponerte para recibir el ataque." ],
			  ltalentos: [ "Salvación" ],
              salvacion: "Fortaleza",
              pg: 15,
			  descripcion: "",
			  cita: "No todo son galanterías y actos piadosos, novato. A veces la rectitud debe defenderse con un brazo fuerte. Vuelve a tomar ese escudo y ponte en guardia de nuevo",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
			{
			  nombre : "Bárbaro",
			  claves : [ "[Luchador]" ],
			  armadura : "",
              escudo : "",
			  armas : [ [ "Gran hacha" ] ],
			  equipo: [ "Mochila", "Odre", "Poción de curación" ],
			  competencias: [ "Armaduras ligeras, medianas y escudos", 
                              "Armas simples y marciales, tanto cuerpo a cuerpo como a distancia" ],
			  talentos: [ "<strong>Furia</strong><br/>Usando 1 PE y una acción bonus entras en estado furioso que finaliza tras 1 minuto (cayendo [Inconsciente]) o si termina un turno sin atacar a un enemigo. En ese estado tienes ventaja en pruebas de Fuerza y salvaciones de Fortaleza. i has logrado golpear a un enemigo en tu último turno y este ataca a un aliado que está a menos de 2 metros de tí puedes interponerte para recibir el ataque.",
						"<strong>Resistencia Salvaje</strong><br/>Tu CA es de 10 + DES + CON cuando no llevas armadura. Puedes usar escudo y seguir manteniendo este beneficio." ],
			  ltalentos: [ "Furia", "Resistencia Salvaje" ],
              salvacion: "Fortaleza",
              pg: 15,
			  descripcion: "",
cita: "¿Qué miras? ¡Lárgate antes de que te machaque la cabeza! ¿Lo ves? Ahora voy a tener que borrarte tu estúpida cara a puñetazos",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
			{
			  nombre : "Bardo",
			  claves : [ "[Bribón]" ],
			  armadura : "Armadura de cuero",
              escudo : "",
			  armas : [ [ "Daga", "Daga" ], [ "Espada corta" ] ],
			  equipo: [ "Intrumento musical", "Manta", "Mochila", "Odre" ],
			  competencias: [ "Armaduras ligeras y escudos pequeños", 
                              "Armas simples tanto cuerpo a cuerpo como a distancia. Espada corta, ropera y larga" ],
			  talentos: [ "<strong>Inspiración</strong><br/>Usando 1 PE y una acción bonus puedes elegir a alguien que esté a menos de 24 metros para que gane un dado de inspiración (1d6)",
						"<strong>Magia Arcana</strong><br/>Puedes lanzar conjuros de la Lista de Conjuros de Bardo. El atributo de lanzamiento es el Carisma." ],
			  ltalentos: [ "Inspiración", "Magia Arcana" ],
              salvacion: "Reflejos",
              pg: 9,
			  descripcion: "",
			  cita: "Cuando piensas en un Bardo, te viene a la cabeza gente inofensiva: muchachas danzando en ropa interior, poetas recitando nuevas o ridículos bufones haciendo reír al noble con sus cabriolas, canciones y sátiras. No te fíes de las apariencias",
			  trucos: { numero: 3, trucos: [ "Calentar/Enfriar", "Fulgor", "Ilusión menor", "Impacto verdadero", "Intimidar bestia", "Luces danzantes", "Mano espectral", "Mensaje", "Remendar", "Sonido" ] },
			  conjuros: { numero: 6, conjuros: [ "Caída de pluma", "Comprensión idiomática", "Condena", "Curar heridas", "Detectar magia", "Disfrazarse", "Dormir", "Escritura ilusoria", "Fuego feérico", 
												"Hablar con los animales", "Hechizar persona", "Heroísmo", "Identificar", "Imagen silenciosa", "Onda atronadora", "Palabra sanadora", "Sirviente inadvertido", 
												"Terribles carcajadas", "Zancada prodigiosa" ] },
			},
			{
			  nombre : "Caído",
			  claves : [ "[Maligno]", "[Sacerdote]" ],
			  armadura : "Cota de escamas",
              escudo : "Escudo mediano",
			  armas : [ [ "Espada larga" ] ],
			  equipo: [ "Símbolo impío", "Manta", "Mochila", "Odre" ],
			  competencias: [ "Armaduras ligeras, medianas, pesadas y escudos", 
                              "Armas simples y marciales, tanto cuerpo a cuerpo como a distancia" ],
			  talentos: [ "<strong>Magia Divina</strong><br/>Puedes lanzar conjuros de la Lista de Conjuros de Caído. El atributo de lanzamiento es el Carisma." ],
			  ltalentos: [ "Magia Divina" ],
              salvacion: "Voluntad",
              pg: 12,
			  descripcion: "",
			  cita: "Sirves a una diosa que te ignora. Puedo entenderte, eres tan débil como lo fui yo. Pero entonces descubrí cómo hacer que sean los dioses quienes me sirvan a mí. Ahora soy mucho más poderoso. Te lo demostraré",
			  trucos: { numero: 3, trucos: [ "Explosión Mental", "Guía divina", "Intimidar bestia", "Protección contra la lluvia", "Resistencia", "Soltar", "Sonido", "Toque gélido" ] },
			  conjuros: { numero: -1, conjuros: [ "Ataque Mortal", "Atormentar", "Condena", "Crear o destruir agua", "Detectar el bien", "Detectar magia", "Detectar venenos y enfermedades", 
												"Drenaje", "Escudo de fe", "Hechizar persona", "Infligir heridas", "Orden", "Protección contra el bien", "Vida falsa" ] },
			},
			{
			  nombre : "Cazador de demonios",
			  claves : [ "[Bribón]", "[Maligno]" ],
			  armadura : "Cuero",
              escudo : "",
			  armas : [ [ "Ballesta de mano", "Daga" ] ],
			  equipo: [ "Manta", "Mochila", "Odre" ],
			  competencias: [ "Armaduras ligeras y escudos pequeños", 
                              "Armas simples cuerpo a cuerpo y a distancia, cimitarra, espada corta, espada larga, espada ropera, guja, látigo, tridente y armas marciales a distancia" ],
			  talentos: [ "<strong>Experto en ballestas</strong><br/>Ignoras la clave [Recarga] de cualquier ballesta de mano, ballesta ligera o ballesta pesada. Además, cuando empleas tu acción para realizar un ataque con un arma de una mano, puedes utilizar tu acción bonus para atacar con una ballesta de mano que tengas en la otra mano",
						  "<strong>Magia Limitada</strong><br/>u pacto demoníaco te permite lanzar determinados conjuros de magia limitada, y conoces los conjuros que se indican en la Lista de Conjuros de Cazador de Demonios. Tu atributo de lanzamiento de conjuros es la Inteligencia." ],
			  ltalentos: [ "Experto en ballestas", "Magia Limitada" ],
              salvacion: "Voluntad",
              pg: 9,
			  descripcion: "",
			  cita: "El mayor de los sacrificios no es morir por otro, es convertirte en lo que más odias para alcanzar tu venganza",
			  trucos: { numero: 0, trucos: [ ] },
			  conjuros: { numero: -1, conjuros: [ "Atormentar", "Condena", "Detectar el bien", "Detectar el mal", "Dormir", "Identificar", "Infligir heridas", 
												  "Manos ardientes", "Nube brumosa", "Protección contra el bien", "Protección contra el mal", "Salto", "Terribles carcajadas" ] },
			},
			{
			  nombre : "Clérigo",
			  claves : [ "[Bueno]", "[Sacerdote]" ],
			  armadura : "Cota de escamas",
              escudo : "Escudo mediano",
			  armas : [ [ "Maza" ] ],
			  equipo: [ "Símbolo sagrado", "Manta", "Mochila", "Odre" ],
			  competencias: [ "Armaduras ligeras, medianas, pesadas y escudos", 
                              "Bastones, clavas, grandes clavas, látigos, martillos de guerra, martillos ligeros, mayales, mazas, mutiladoras, redes" ],
			  talentos: [ "<strong>Magia Divina</strong><br/>Puedes lanzar conjuros de la Lista de Conjuros del Clérigo. El atributo de lanzamiento es la Sabiduría." ],
			  ltalentos: [ "Magia Divina" ],
              salvacion: "Voluntad",
              pg: 12,
			  descripcion: "",
			  cita: "Yo vivo para servir al reino y a la Diosa. No espero a cambio ni una bolsa de oro, ni ser recordado. ¿Alguno de vosotros osa dudar de mi compromiso con este viaje?",
			  trucos: { numero: 3, trucos: [ "Expiación", "Fuego sagrado", "Fulgor", "Guía divina", "Protección contra la lluvia", "Remendar", "Resistencia", "Soltar", "Sonido" ] },
			  conjuros: { numero: -1, conjuros: [ "Bendición", "Condena", "Crear o destruir agua", "Curar heridas", "Detectar el mal", "Detectar magia", "Detectar venenos y enfermedades", "Escudo de fe", "Infligir heridas", "Orden", "Palabra sanadora", "Protección contra el mal", "Purificar comida y bebida", "Rayo guiado", "Santuario" ] },
			},
			{
			  nombre : "Duelista",
			  claves : [ "[Bribón]" ],
			  armadura : "Cuero",
              escudo : "",
			  armas : [ [ "Espada ropera", "Daga" ] ],
			  equipo: [ "Manta", "Mochila", "Odre" ],
			  competencias: [ "Armaduras ligeras y medianas", "Armas simples cuerpo a cuerpo y a distancia. Espadas cortas, largas y roperas" ],
			  talentos: [ "<strong>Maniobras de duelista</strong><br/>Gastando un punto de duelista (inicialmente 3) puede activar una de las siguientes maniobras:<br/> - Balestra: Puedes hacer un ataque adicional al mismo rival o a otro que esté a un máximo de 3 metros.<br/> - Parar: ante un ataque, como reacción puedes agregar DES a tu CA para ese ataque.<br/> - Estocada: Si tu rival falla el ataque cuerpo a cuerpo puedes usar tu reacción para atacarle.<br/>Tras un descanso se recuperan tantos puntos de duelista como la mitad del total redondeado hacia abajo." ],
			  ltalentos: [ "Maniobras de duelista" ],
              salvacion: "Reflejos",
              pg: 9,
			  descripcion: "",
			  cita: "Tú mataste a mi padre. Prepárate a morir",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
			{
			  nombre : "Druida",
			  claves : [ "[Sacerdote]" ],
			  armadura : "Cuero",
              escudo : "Escudo pequeño",
			  armas : [ [ "Lanza" ] ],
			  equipo: [ "Símbolo sagrado", "Manta", "Mochila", "Odre" ],
			  competencias: [ "Armaduras ligeras, armaduras medias y escudos (ninguno de metal)", 
                              "Bastones, clavas, grandes clavas, látigos, martillos de guerra, martillos ligeros, mayales, mazas, mutiladoras, redes" ],
			  talentos: [ "<strong>Magia Divina</strong><br/>Puedes lanzar conjuros de la Lista de Conjuros del Druida. El atributo de lanzamiento es la Sabiduría." ],
			  ltalentos: [ "Magia Divina" ],
              salvacion: "Voluntad",
              pg: 12,
			  descripcion: "",
			  cita: "La gente pasa a diario junto al prado y se pregunta qué hago ahí, descalzo, medio desnudo y tendido con los ojos cerrados sobre la hierba. Creen que no me entero de cómo se refieren a mí. Pero yo no estoy loco. A diferencia de ellos, siento el Equilibrio",
			  trucos: { numero: 3, trucos: [ "Aumentar peso", "Calentar/Enfriar", "Guía divina", "Intimidar bestia", "Jugar con fuego", "Remendar", "Resistencia", "Sonido", "Soplo de viento" ] },
			  conjuros: { numero: -1, conjuros: [ "Crear o destruir agua", "Curar heridas", "Detectar magia", "Detectar venenos y enfermedades", "Escudo de fe", "Enraizar", "Fuego feérico" , "Hablar con los animales", "Hechizar persona", "Nube brumosa", "Onda atronadora", "Purificar comida y bebida", "Revitalizar", "Salto", "Zancada prodigiosa" ] },
			},
			{
			  nombre : "Explorador",
			  claves : [ "[Luchador]" ],
			  armadura : "Cuero",
              escudo : "",
			  armas : [ [ "Arco corto", "Daga" ] ],
			  equipo: [ "Mochila", "Odre", "Manta" ],
			  competencias: [ "Armaduras ligeras, medianas y escudos", 
                              "Armas simples a distancia, armas marciales cuerpo a cuerpo, armas marciales a distancia." ],
			  talentos: [ "<strong>Cazador de monstruos</strong><br/>Tienes ventaja en las tiradas de Sabiduría y de Inteligencia para rastrear y recabar información sobre las criaturas con una de las siguientes claves: [Aberración], [Bestia], [Feérico], [Gigante], [Monstruosidad] o [Trasgo]. Una vez por turno, cuando ataques con un arma a una criatura con la clave elegida, puedes volver a tirar los dados de la tirada de daño y usar cualquiera de los dos resultados.",
						"<strong>Guía experto</strong><br/>Si guías a tu grupo por territorio salvaje, este no se puede perder salvo por intervención mágica. Además, cuando forrajeas, encuentras el doble de alimento de lo que encontraría cualquier otro." ],
			  ltalentos: [ "Cazador de monstruos", "Guía experto" ],
              salvacion: "Fortaleza",
              pg: 15,
			  descripcion: "",
			  cita: "Todo lo que sé lo aprendí solo, con paciencia y silencio. Paciencia para comprender el lenguaje de las huellas y no soltar la cuerda del arco antes de tiempo. Silencio para no advertir a las presas y moverme sin contratiempos",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
			{
			  nombre : "Guardián Arcano",
			  claves : [ "[Mago]" ],
			  armadura : "Cuero",
              escudo : "",
			  armas : [ [ "Cimitarra" ], [ "Espada corta" ], [ "Espada larga" ], [ "Espada ropera" ], [ "Gran hacha" ], [ "Hacha de batalla" ], [ "Daga", "Daga" ], [ "Hacha de mano", "Lanza" ], [ "Hoz", "Jabalina" ] ],
			  equipo: [ "Manta", "Mochila", "Odre" ],
			  competencias: [ "Armaduras ligeras y escudos", 
                              "Armas simples cuerpo a cuerpo, armas simples a distancia, un arma marcial cuerpo a cuerpo de tu elección, un arma marcial a distancia de tu elección." ],
			  talentos: [ "<strong>Forja élfica</strong><br/>Has sido bendecido con el saber de los antiguos guerreros de los altos elfos, y eres capaz de vincular un arma o armadura a tu esencia feérica con tan solo emplear 1 hora de meditación.<br/>- Cada vez que realices daño con tu arma vinculada, causas tanto daño místico adicional como se indica en la Tabla de Progreso de Guardián Arcano.<br/>- Cuando llevas tu armadura vinculada consideras los impactos críticos que te realicen como impactos normales.", 
						  "<strong>Magia limitada</strong><br/>Tu linaje élfico te permite lanzar determinados conjuros de magia limitada, y conoces los conjuros que se indican en la Lista de Conjuros de Guardián Arcano. Tu atributo de lanzamiento de conjuros es la Inteligencia." ],
			  ltalentos: [ "Forja élfica", "Magia limitada" ],
              salvacion: "Voluntad",
              pg: 9,
			  descripcion: "",
			  cita: "No intentes huir. Una vez has sido marcado por la casa Arquenion, tu destino está sellado",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: -1, conjuros: [ "Armadura de mago", "Detectar magia", "Disco flotante", "Dormir", "Explosión de Escarcha", "Grasa", "Identificar", "Manos ardientes", "Protección contra el mal", "Salto" ] },
			},
			{
			  nombre : "Guerrero",
			  claves : [ "[Luchador]" ],
			  armadura : "Cota de escamas",
              escudo : "Escudo mediano",
			  armas : [ [ "Espada larga" ] ],
			  equipo: [ "Mochila", "Odre", "Manta" ],
			  competencias: [ "Armaduras ligeras, medianas, pesadas y escudos", 
                              "Armas simples y marciales tanto cuerpo a cuerpo como a distancia" ],
			  talentos: [ "<strong>Entrenamiento Marcial</strong><br/>Eres un experto combatiente, capaz de poner lo mejor de ti mismo en cada golpe que das. No sumas tu bono de competencia al impacto cuando realizas un ataque con un arma. En su lugar, tira el Dado de Combate que corresponda a tu nivel en la Tabla de Progreso de Guerrero y añade el resultado al impacto y al daño.",
						"<strong>Recuperación</strong><br/>Puedes gastar 1 PE y emplear una acción bonus para realizar un movimiento defensivo y recuperar parte de los daños sufridos por el combate. Recuperas tantos PG como el resultado en tu Dado de Combate (d4) + tu nivel" ],
			  ltalentos: [ "Entrenamiento Marcial", "Recuperación" ],
              salvacion: "Fortaleza",
              pg: 15,
			  descripcion: "",
			  cita: "Provocarás tu propio sufrimiento solo por saborear la efímera gloria de vencer a tu oponente",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
			{
			  nombre : "Hechicero",
			  claves : [ "[Mago]" ],
			  armadura : "",
              escudo : "",
			  armas : [ [ "Bastón" ], [ "Daga" ] ],
			  equipo: [ "Libro de conjuros", "Manta", "Mochila", "Odre", "Poción de curación" ],
			  competencias: [ "Bastones, ballestas ligeras, dagas, dardos y hondas" ],
			  talentos: [ "<strong>Extracción</strong><br/>Estás aprendiendo a entender la mismísima esencia del poder mágico. Concentrándote y meditando durante 1 minuto, eres capaz de extraer tu propia vitalidad y convertirla en Poder vivo. Puedes gastar 1 PE para recuperar tanto Poder como tu nivel.", 
						  "<strong>Magia arcana</strong><br/>Como sabio y experto en el poder arcano, eres capaz de lanzar conjuros de todo tipo. Empleas magia arcana, y puedes llegar a conocer los conjuros que se indican en la Lista de Conjuros de Hechicero. Tu atributo de lanzamiento de conjuros es la Inteligencia. Posees un libro de conjuros que necesitas repasar cada mañana. De no poder hacerlo, no podrás lanzar conjuros de Rango 1 o superior." ],
			  ltalentos: [ "Extracción", "Magia arcana" ],
              salvacion: "Voluntad",
              pg: 9,
			  descripcion: "",
			  cita: "¿Acaso crees que esto va de poder? ¡No! Esto va de conocimiento, de comprensión de la naturaleza de las cosas, del tejido de la realidad que nos envuelve. El poder es solo un efecto secundario de la comprensión... ¡Humanos! ¡Siempre tan impacientes! ¡Deja esos trucos de salón antes de que decida que estoy perdiendo el tiempo contigo!",
			  trucos: { numero: 3, trucos: [ "Aumentar peso", "Calentar/Enfriar", "Contacto electrizante", "Fulgor", "Ilusión menor", "Impacto verdadero", 
											 "Jugar con fuego", "Luces danzantes", "Mano espectral", "Mensaje", "Protección contra la lluvia", "Rayo de escarcha", 
											 "Rayo de fuego", "Remendar", "Salpicadura de ácido", "Sonido", "Soplo de viento", "Toque gélido", "Zancada fantasma" ] },
			  conjuros: { numero: 6, conjuros: [ "Alarma", "Armadura de mago", "Caída de pluma", "Comprensión idiomática", "Detectar magia", "Disco flotante", "Disfrazarse", 
												 "Dormir", "Escritura ilusoria", "Escudo", "Explosión de Escarcha", "Grasa", "Hechizar persona", "Identificar", "Imagen silenciosa", 
												 "Manos ardientes", "Nube brumosa", "Onda atronadora", "Orbe cromático", "Protección contra el mal", "Proyectil mágico", "Retirada expeditiva", 
												 "Rociada de color", "Salto", "Sirviente inadvertido", "Terribles carcajadas", "Vida falsa", "Zancada prodigiosa" ] },
			},
			{
			  nombre : "Hoja de Otoño",
			  claves : [ "[Bribón]" ],
			  armadura : "",
              escudo : "",
			  armas : [ [ "Filo otoñal", "Filo otoñal" ] ],
			  equipo: [ "Manta", "Mochila", "Odre" ],
			  competencias: [ "Armas simples cuerpo a cuerpo  y a distancia. Arcos largos, Espadas cortas y largas y filos otoñales" ],
			  talentos: [ "<strong>Corte Otoñal</strong><br/>Puedes cargar a una velocidad imposible en línea recta, arrasando con tus filos otoñales todo lo que hay en el camino. Una vez por turno, puedes realizar Corte Otoñal, acción con la que te desplazas 8 metros en línea recta sin generar ataques de oportunidad. Además, todas las criaturas que estén a un máximo de 2 metros del lugar por el que hayas pasado, deben superar una salvación de Reflejos con CD igual a 8 + tu bono de competencia + tu DES o sufrirán tantos d6 de daño cortante como tu nivel de Hoja de Otoño.<br/>Puedes utilizar Corte Otoñal siempre y cuando sostengas un arma [Ligera] y [Sutil] en cada mano. No obstante, si las armas no son filos otoñales, las criaturas afectadas tendrán ventaja en la salvación de Reflejos.",
						"<strong>Viento de Invierno</strong><br/>Eres excepcionalmente rápido. Todos los ataques a distancia que te tengan como objetivo tienen desventaja y obtienes ventaja en todas las salvaciones de Reflejos. No te beneficias de este talentos si estás [Apresado], [Aturdido], [Derribado], [Frenado] o [Paralizado]" ],
			  ltalentos: [ "Corte Otoñal", "Viento de Invierno" ],
              salvacion: "Reflejos",
              pg: 9,
			  descripcion: "",
			  cita: "No estás preparado para enfrentarte a mí. No digas que no te lo advertí",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
			{
			  nombre : "Irredento",
			  claves : [ "[Luchador]" ],
			  armadura : "",
              escudo : "",
			  armas : [ [ "Gran hacha" ] ],
			  equipo: [ "Mochila", "Odre", "Manta" ],
			  competencias: [ "Armas simples cuerpo a cuerpo y a a distancia y marciales cuerpo a cuerpo" ],
			  talentos: [ "<strong>Maldición del Rompejuramentos</strong><br/>Fallaste a tu pueblo y ahora estás maldito por tu juramento. Ahora, tu única esperanza de restaurar tu nombre es morir en un glorioso combate. Este talento te otorga los siguientes beneficios y perjuicios: <br/>- Por cada 10 PG de diferencia entre tus PG y tus PG máximos, puedes añadir 1d6 al daño cuando realizas un ataque cuerpo a cuerpo con arma [A Dos Manos]. <br/>- Cuando tus PG descienden a 0, cualquier intento ajeno a ti de curarte o estabilizarte es infructuoso y no tiene efecto. <br/>- No se te puede resucitar, ya que una vez has muerto en glorioso combate has alcanzado la redención y la paz en Otromundo." ],
			  ltalentos: [ "Maldición del Rompejuramentos" ],
              salvacion: "Fortaleza",
              pg: 15,
			  descripcion: "",
			  cita: "Prometí proteger a mi pueblo o morir. Por lo que a mí respecta, ya estoy muerto, así que ni se te ocurra ponerme esa venda",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
			{
			  nombre : "Pícaro",
			  claves : [ "[Bribón]" ],
			  armadura : "Cuero",
              escudo : "",
			  armas : [ [ "Espada corta", "Daga" ], [ "Daga", "Daga" ] ],
			  equipo: [ "Manta", "Mochila", "Odre" ],
			  competencias: [ "Armaduras ligeras y escudos pequeños", 
							  "Armas simples cuerpo a cuerpo y a distancia. Ballestas de mano, Espadas cortas, largas y roperas" ],
			  talentos: [ "<strong>Ataque Furtivo</strong><br/>Sabes cómo atacar sutilmente y aprovechar las distracciones de tu oponente. Una vez por turno, si tienes ventaja en la tirada de ataque puedes infligir tantos d6 de daño adicional como tu nivel de pícaro. También puedes emplear Ataque Furtivo si atacas a un enemigo que esté a menos de 2 metros de uno de tus aliados. El ataque debe realizarse con un arma que posea las claves [Sutil] o [A Distancia].",
						"<strong>Especialista</strong><br/>Eres capaz de realizar algunas tareas de dudosa moralidad con extrema facilidad. Cada vez que haces una prueba de atributo de Inteligencia relacionada con buscar trampas o puertas secretas, o una prueba de atributo de Destreza relacionada con abrir cerraduras, desactivar trampas, escapismo, esconderse, robar o moverse sigilosamente; puedes añadir tu bono de competencia al resultado de la prueba. Si ya eras competente en el atributo correspondiente, doblas el bono de competencia." ],
			  ltalentos: [ "Ataque Furtivo", "Especialista" ],
              salvacion: "Reflejos",
              pg: 9,
			  descripcion: "",
			  cita: "Guárdate de Puertoceniza. En especial de los mendigos mutilados, los niños perdidos y las jovencitas en apuros. No dudarán en liberarte del peso de tu bolsa. Aún así, es un buen lugar para alquilar gentuza sin escrúpulos...",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
			{
			  nombre : "Pionero",
			  claves : [ "[Luchador]" ],
			  armadura : "Cuero",
              escudo : "",
			  armas : [ [ "Hacha de batalla", "Ballesta ligera" ] ],
			  equipo: [ "Mochila", "Odre", "Manta" ],
			  competencias: [ "Armaduras ligeras, medianas y escudos", 
							  "Armas simples y marciales cuerpo a cuerpo y a distancia." ],
			  talentos: [ "<strong>Bolsa Mágica</strong><br/>Tienes una Bolsa Mágica llena de útiles heredados de tus familiares caídos. Una vez por día, cuando necesites cualquier objeto no perecedero que se te ocurra y que no sea mágico, puedes emplear 1 minuto buscando en la Bolsa Mágica. La probabilidad de encontrar ese objeto depende de tu nivel, tal y como se muestra en la Tabla de Progreso de Pionero (50% nivel 1).<br/> La bolsa está vacía a ojos de cualquier persona que no pertenezca a tu familia. Si no devuelves los objetos a la bolsa antes de 24 horas, deshonrarás a tus ancestros y te retirarán el acceso a la Bolsa Mágica.",
						  "<strong>Sabia Herencia</strong><br/>Cada vez que te encuentres con una criatura puedes emplear una acción para pedir a tus ancestros información sobre la especie de la criatura. La probabilidad de que te hagan caso depende de tu nivel, tal y como se muestra en la Tabla de Progreso de Pionero (35% nivel1)"],
			  ltalentos: [ "Bolsa Mágica", "Sabia Herencia" ],
              salvacion: "Fortaleza",
              pg: 15,
			  descripcion: "",
			  cita: "Esto no son bártulos: es mi mochila, y llevo cosas realmente útiles en ella. A ver déjame un segundo que busque... ¿Te hacía falta una pipa, no? ¡Acabo de encontrar la de mi abuelo! Está un poco vieja pero es de muy buena manufactura...",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
			{
			  nombre : "Señor de las Bestias",
			  claves : [ "[Luchador]" ],
			  armadura : "Cuero",
              escudo : "",
			  armas : [ [ "Arco corto", "Lanza" ] ],
			  equipo: [ "Mochila", "Odre", "Manta" ],
			  competencias: [ "Armaduras ligeras, medianas y escudos", 
							  "Armas simples y marciales cuerpo a cuerpo y a distancia." ],
			  talentos: [ "<strong>Compañero Animal</strong><br/>Has trabado un fuerte vínculo con una criatura animal. Te acompañará allí donde vayas y confiará en ti hasta el punto de poner su vida en riesgo, si fuera necesario. Puedes escoger como compañero animal cualquier criatura con la clave [Bestia] de un nivel inferior o igual al tuyo. Interactuas con tu compañero animal empleando tu acción bonus para ordenarle mentalmente que se mueva y realice una acción o empleando tu reacción para ordenarle que emplee una reacción.<br/>El nivel de tu compañero animal siempre es igual a tu nivel de señor de las bestias.<br/>A tu compañero animal se le aplican las mismas reglas de descanso y muerte que a los personajes. Si muere, no podrás sustituirlo hasta pasadas dos semanas."],
			  ltalentos: [ "Compañero Animal" ],
              salvacion: "Fortaleza",
              pg: 15,
			  descripcion: "",
			  cita: "¿Cómo que no podemos pasar? ¿Eh? ¿Por la bestia? No es una bestia es mi amigo. ¡Y se llama Coco! Oye, si Coco no entra yo tampoco. Además tu taberna está mugrienta y todo es muy caro",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
			{
			  nombre : "Vagarr",
			  claves : [ "[Luchador]" ],
			  armadura : "Cuero",
              escudo : "",
			  armas : [ [ "Arco corto" ], [ "Espadón" ] ],
			  equipo: [ "Mochila", "Odre" ],
			  competencias: [ "Armaduras ligeras, medianas y escudos", 
							  "Armas simples y marciales cuerpo a cuerpo y a distancia." ],
			  talentos: [ "<strong>Elegido</strong><br/>Puedes repetir cualquier tirada de ataque, salvación, prueba de atributo, o tirada de daño cuyo resultado en el dado sea de 1. Solo puedes repetir cada tirada una vez.", 
						  "<strong>Las Tres Sendas</strong><br/>Escoge la senda del águila, lobo u oso.<br/>La Senda del Águila. Tienes ventaja en las pruebas de atributo <br/>- La Senda del Águila. Tienes ventaja en las pruebas de atributo de Sabiduría relacionadas con la vista y puedes ver en la oscuridad en un radio de 24 metros. Además, cuando atacas a distancia puedes escoger penalizar con un -5 tu tirada de impacto para obtener +10 al daño. <br/>- La Senda del Lobo. Pierdes tus competencias en armas cuerpo a cuerpo y obtienes ventaja en las pruebas de atributo de Sabiduría relacionadas con el oído y el olfato. Empleando una acción bonus y 1 PE puedes convertir tus manos en las Garras del Lobo. Cada garra se considera un arma cuerpo a cuerpo [Ligera] que causa daño cortante. Consulta el daño que realizas en función de tu nivel en la Tabla de Progreso de Vagarr (1d6 a nivel 1). Puedes emplear otra acción bonus para hacer desaparecer las garras. <br/>- La Senda del Oso. Pierdes todas tus competencias en armaduras y escudos. La Piel del Oso te otorga resistencia al daño contundente, ventaja en las salvaciones de Fortaleza y aumenta tu CA hasta la cantidad indicada para tu nivel en la Tabla de Progreso de Vagarr (15 a nivel 1). No puedes sumar tu DES a la CA." ],
			  ltalentos: [ "Elegido", "Las Tres Sendas" ],
              salvacion: "Fortaleza",
              pg: 15,
			  descripcion: "",
			  cita: "Soy un hombre, pero también soy una bestia. Vivimos en un equilibrio perfecto: yo la alimento y ella me presta lo que necesito. Como estas garras, que te van a destrozar la garganta",
			  trucos: { numero: 0, trucos: [ "" ] },
			  conjuros: { numero: 0, conjuros: [ "" ] },
			},
		]
	}
	
	get clases() {
		return this._clases;
	}

	set clases(value) {
		this._clases = value;
	}
	
	clase(nombre) {
		var iclases=0;
		for (iclases=0; iclases<this._clases.length; iclases++) {
			if ( this._clases[iclases].nombre == nombre ) {
				return new Clase(this._clases[iclases]);
			}
		}
		return new Clase(this._clases[Comun.random(this._clases.length, 0)]);
	}
}
