
class Trasfondos {
	constructor() {
		this._trasfondos = [ "Usted es un paria de su tribu anterior y se ha visto obligado a hacer un nuevo hogar en una nueva tierra. ¿Cómo te convertiste en un paria? Cual fue el crimen? ¿Quién te acusó y por qué?",
							"Fuiste abandonado en los bosques o en los bosques por tus padres y criado por el druida local o (si es sajón, chamán). Puedes elegir la profesión de druida, chamán, bardo o escaldo si lo deseas. ¿Por qué te abandonaron tus padres? ¿Todavía viven? ¿Cómo te sientes por ellos?",
							"Mataste o lesionaste accidentalmente a un amigo de la infancia. Gana un enemigo, ya sea el niño herido o uno de sus hermanos. Tienen la intención de causarle daño en el futuro.",
							"Eres sajón de nacimiento (o celta, si estás en un juego sajón) y eres salvado por las personas a las que ahora llamas tu familia. Hablas la lengua sajona y tienes el aspecto sajón, pero te consideras un británico (o un sajón). No sientes nada por tus ancianos, ¿o sí?",
							"Un objeto de valor incalculable (espada, armadura o joyas) que pertenecía o estaba protegido por su familia fue robado por enemigos. Has jurado recuperarlo de los ladrones.",
							"Está afligido por la pasión por los viajes y nunca ha permanecido más de un año en un solo lugar. Por lo tanto, ha viajado mucho, pero no tiene una familia real ni raíces: esto hace que algunas personas desconfíen de usted.",
							"Un hermano se ha comprometido con alguien de tu infancia a quien consideras un enemigo. Te ves obligado a hacer las paces con este nuevo suegro, pero tu odio aún arde debajo. Lo peor es que temes que tu hermano se vuelva en tu contra. ¿Qué puedes hacer para arreglar las cosas?",
							"Crees que estás sufriendo una maldición divina o mágica. Gime, gime y lloriquea en cada oportunidad, o permanece completamente estoico ante cada desgracia que te ocurra en el futuro. ¿Quién te maldijo? ¿Por qué? ¿Cristiano o pagano?",
							"Ha hecho un juramento para completar una tarea para un miembro de la familia moribundo. Cual es la tarea? ¿Es simple o complicado, seguro o peligroso? ¿Tardará años en completarse o en cuestión de semanas? ¿Qué ayuda podrías necesitar? ¿Qué pasa si fallas?",
							"Un bardo/escaldo, sacerdote o druida visita tu comunidad y demuestra una sabiduría casi sobrenatural. Estás fascinado por lo que ves, pero el individuo no permanece el tiempo suficiente para que aprendas más. Sin embargo, recibes sueños que muestran que te encuentras con esta persona nuevamente y aprendes de él. Cuándo, dónde y cómo formarán una parte futura de su historia.",
							"Como es común entre los celtas, te enviaron a vivir con una familia adoptiva en un pueblo diferente. Tu familia de acogida fue fría y distante contigo: a veces muy cruel. Al regresar a su verdadera familia, también se habían distanciado de usted. ¿Cuál es la raíz de esta extrañeza? ¿Por qué te han atrapado en el medio?",
							"El destino te ha vigilado de cerca a medida que te convertiste en adulto. Los hermanos se han ahogado, los amigos han muerto de peste, los padres han caído en desgracia, pero tú has salido ileso de todo. ¿Estás verdaderamente bendecido por los dioses (o por Dios)?",
							"Naciste con una característica prominente y distintiva que ahora te proporciona un apodo de por vida (Owain Big-Nose, por ejemplo; o Erik the Wide).",
							"Los espíritus te han favorecido, incluso si eres cristiano y no crees en ellos. Puedes verlos y ellos pueden verte a ti. No puedes comandarlos, pero puedes comunicarte con ellos. Que mientan o no depende de si haces una tirada de superstición con éxito ... ¿es este poder algo que debes mantener en secreto o compartir?",
							"Fuiste intimidado brutalmente cuando crecías. Ahora que eres maduro, es el momento de la venganza. Pero, ¿quiénes fueron los matones y qué forma tomará esa venganza?",
							"Fuiste rehén o rescatado cuando eras joven, un peón utilizado por otros en alguna disputa familiar. Tu corazón te dice que odies a los que te tuvieron como rehén, pero, en verdad, fueron amables contigo y llegaste a amarlos. Cuando se cumplió la obligación, no quisiste irte. ¿Te fuiste? Si regresó con su familia, ¿cómo se siente ahora por ellos?",
							"De alguna manera, ha recogido a un compañero o criado leal. Quizás un amigo de la infancia; quizás un parásito de algún encuentro fortuito. Esto no necesariamente hace que su compañero sea una presencia bienvenida, pero la relación de alguna manera ha perdurado a lo largo de los años.",
							"Tu aldea fue atacada por el enemigo. Viste la masacre de tu familia. Eras demasiado joven para hacer algo. El druida o sacerdote que dirigió los viles sacrificios que siguieron te vio, se rió, pero te dejó vivir como el único superviviente de la carnicería para contarle a los demás lo que viste. Encontrarás a ese mago un día y lo matarás.",
							"Los dioses o Dios te han marcado como especial. Lleva consigo un símbolo o marca que es de gran reverencia a su religión. Puede ser un tesoro religioso o una reliquia sagrada. Sea lo que sea, otros (druidas, sacerdotes, hechiceros, chamanes) lo quieren y no se detendrán ante nada para conseguirlo. ¿Qué es? ¿Cómo lo proteges? ¿Por qué lo quieren?",
							"Tienes una mascota predilecta y querida que te sigue a todas partes. No tiene habilidades ni poderes especiales, pero ofrece comodidad y compañía.",
							"Se le considera un héroe en su comunidad local, o se le considera con especial reverencia. ¿Qué hiciste? ¿Cómo lo hiciste? ¿Eres digno de toda esta atención?",
							"Cegado de un ojo, ya sea por accidente o por un acto de crueldad. Puede utilizar el sobrenombre 'Un ojo', aunque su ceguera no afecta su vida diaria en general.",
							"Alguien de tu familia era un ladrón y perdió una mano por ello. La reputación se ha quedado, lamentablemente, y cada vez que algo se pierde, todos los ojos se vuelven hacia ti, a pesar de que eres completamente inocente. ¿Cómo lidias con este estigma?",
							"Tienes un parecido asombroso con alguien rico, famoso o poderoso: tal vez un señor, un héroe, líder de una banda de guerra o incluso un druida, sacerdote o enemigo de tu tribu. ¿Es esto una bendición o una maldición? ¿Puedes usarlo a tu favor de alguna manera?",
							"Tu familia está involucrada en una Blood Feud con una familia de un clan rival en la misma tribu. Durante varios años ninguna de las partes ha tomado ninguna medida, pero recientemente sus enemigos han sido provocadores, tratando de reavivar el derramamiento de sangre. ¿Qué inició la pelea? ¿Qué venganza deberías tomar? ¿No sería mejor resolver la disputa antes de que se derrame más sangre?",
							"Después de un concurso de bebidas, descubrió que nunca sufre de resaca, no importa qué beba, cuánto o qué tan rápido. Siempre te despiertas al día siguiente tan fresco como siempre, para sorpresa y disgusto de tus amigos.",
							"De niño fuiste testigo de algún tipo de delito. No pudiste dar testimonio y el criminal se salió con la suya. ¿Quién fue el criminal? ¿Cuál fue su crimen? Todavía te miran, y ahora que eres mayor, existe la posibilidad de que intenten silenciarte por completo. ¿A qué te dedicas?",
							"Todos los miembros de su familia no han vivido más allá de los 30 años. Las causas de muerte son muchas y variadas, pero todos piensan que su linaje está maldito. Esto significa que no es una buena perspectiva de matrimonio. ¿Cómo se puede levantar la maldición? ¿Quién maldijo a tu familia? ¿Cuánto tiempo te queda?",
							"Cuando eras niño, casi mueres de una enfermedad fatal, pero desde entonces nunca has estado enfermo. ¿Está simplemente paranoico con cualquier tipo de infección o cree que es inmune a cualquier forma de contagio?",
							"Un pariente que había abrazado el cristianismo y era un ardiente seguidor de Cristo, de repente se ha retractado de sus puntos de vista y ha abrazado el paganismo con renovado fervor. ¿Por qué es esto? ¿Es una señal de que la religión cristiana no tiene un poder real en Britania? Si eres cristiano, ¿cómo te sientes con esta conversión repentina?",
							"Varios parientes han abrazado el cristianismo y se han sometido al bautismo. Ahora te instan a que hagas lo mismo. Si ya eres cristiano, te exhortan a donar todas tus posesiones mundanas a la Iglesia, porque Dios ama a los pobres y a los que piensan más en los demás que en ellos mismos. ¿Cómo te sientes al respecto? ¿Harás lo que ellos quieran?",
							"Te has convertido en enemigo del sacerdote o druida local, sin importar cuál sea tu religión. ¿Qué hiciste para ofenderlo? ¿Cómo puedes hacer las paces? ¿Quieres? El sacerdote o el druida pueden causarle muchos problemas, ¿cómo va a lidiar con eso?",
							"Creciste o naciste mudo, pero aún eres capaz de comunicarte con lenguaje de señas o gruñidos: usa la habilidad Danza para transmitir ideas complejas.",
							"Tu familia fue perseguida por enemigos poderosos. ¿Por qué fue esto? ¿Por qué su familia necesitaba seguir moviéndose y escondiéndose? ¿Qué quieren los perseguidores? ¿Todavía te siguen? ¿Deberías confrontarlos? Estás harto y cansado de estar huyendo.",
							"Eres un hijo de puta. Tu madre jura que tu padre era un hombre destacado y de posición, pero ella misma tiene un estatus bajo y tú eres considerado incluso más bajo que ella. Nadie sabe dónde está tu padre, pero te encantaría conocerlo algún día y descubrir la verdad sobre él. Quizás, si se reúne con su padre, el estigma de su nacimiento podría borrarse.",
							"Tienes una deformidad física grotesca de una ubicación aleatoria; sin efectos nocivos, ya que has aprendido a adaptarte, pero debes mantener la deformidad oculta para evitar causar horror o disgusto. Sin embargo, tu deformidad es considerada una bendición por un druida local, una marca de los dioses. ¿Cómo reaccionas a esto? ¿Te hace especial o más miserable? Depende mucho de tu religión.",
							"Cuando era niño, tropezó con un tesoro de monedas enterrado por los romanos y olvidado cuando huyeron de Britania. Allí hay suficiente plata para mantenerte en el lujo durante muchos años. Por derecho, debe declararse a su tribu y convertirse en riqueza comunal, pero usted se ha mostrado reacio a hacerlo. Tampoco ha podido gastar el dinero porque generará preguntas. ¿Qué vas a hacer? ¿En quién puedes confiar?",
							"Estás desesperadamente enamorado de alguien de tu comunidad inmediata. Él o ella solo aceptará tu amor si demuestras que eres digno. Esto podría ser valor en la batalla, emprender una expedición o búsqueda peligrosa u obtener algo que el objeto de tu amor desea y desea. Hay mucha competencia por sus afectos. ¿Cómo estará a la altura de las expectativas?",
							"En un ataque de ira, maldijo a alguien con quien estaba temporalmente enojado. Dos días después, esa persona murió en circunstancias trágicas. Todos te culpan de la muerte y tú incluso te culpas a ti mismo. Sientes que debes expiar la maldición: ¿cómo lo haces? ¿Qué se espera de ti?",
							"Eres un gemelo. Tu hermano o hermana tiene características y habilidades similares a las tuyas, pero claramente sois personas diferentes. ¿Estás cerca, como suelen ser los gemelos, o estás separado? Siempre parece saber dónde está su hermano, incluso si las relaciones entre ustedes no son buenas.",
							"Los comentarios inadvertidos dieron como resultado una pelea, batalla o guerra; el comentario o la acción fueron inocentes pero las repercusiones trágicas. ¿Cuáles fueron los comentarios? ¿Sigues teniendo la culpa?",
							"Conociste a un gran héroe (o villano) en un momento en el que era desconocido. Quizás sospechabas que esta persona estaba destinada a la grandeza (o la infamia), pero aun así te hiciste amigos antes de separarte. ¿Te recordarán? ¿Seguirán siendo amigos?",
							"Alguien de poder e influencia en su comunidad le ha dado brillo. Automáticamente se convierten en aliados y hablarán en tu defensa u ofrecerán ayuda si es necesario. De vez en cuando se espera que pague estos favores, pero no le importa. Es bueno tener amigos en las altas esferas.",
							"Tu madre desapareció inmediatamente después de que nacieras. Has aprendido por un pariente que no era un humano en absoluto, sino un semidiós, que visitaba el Mundo Mortal por curiosidad. Si eres pagano, estas son noticias asombrosas, si es cierto. Si usted es cristiano, es una noticia terrible, terrible y significa que debe buscar la ayuda divina para librarse de la mancha y acercarlo a Cristo. ¿Es verdad lo que te han dicho? ¿Tienes un destino oculto? ¿Aceptas la noticia?",
							"Te aterrorizan los insectos. Puedes enfrentarte a una horda de enemigos, pero las arañas y los bichos espeluznantes te hacen sudar frío.",
							"Tu familia tiene fama de tener suerte. Todo lo que hace su familia resulta espléndido; tiene una riqueza para la que nunca pareció trabajar; tiene una sólida reputación; nunca le ha sucedido ningún mal. Sin embargo, has escuchado algo que te hace sospechar de esta vida encantadora que has llevado. ¿Cómo consiguió tu familia esta suerte? ¿Se pagó un precio mucho más alto, quizás un precio más oscuro?",
							"Tu clan capturó guerreros sajones o celtas que fueron convertidos en esclavos. Uno fue regalado a tu familia y descubriste que este guerrero no era el demonio que todos habían hecho, sino un hombre bueno y amable que simplemente habla un idioma diferente y cree en cosas diferentes. Te volviste amigable y él agradeció las pequeñas amabilidades. De alguna manera se las arregló para escapar y llegó a tu cabaña. 'Te recordaré, pequeño', dijo, 'y seré tu amigo mientras viva. Si alguna vez te encuentras entre mi gente, dales el nombre de Red Mane, todos me conocen, y eso te dará un paso seguro '.",
							"Tu familia siempre fue cruel contigo. No lo sabes, pero tus hermanos siempre parecían recibir un mejor trato y más favores. Siempre te han negado. Por eso, a la primera oportunidad, los dejaste atrás, olvidándolos y buscando la vida de un aventurero.",
							"La sabia mujer local afirma que eres un polimorfo, una criatura inhumana cambiada por un bebé real poco después del nacimiento. Nadie le cree, está bastante, bastante loca; pero siempre pensaste que había algo diferente en ti. Le resulta difícil adaptarse y, a veces, tiene la sensación de que lo están observando, especialmente de noche. ¿Podría la mujer sabia tener razón?",
							"Su familia estuvo involucrada en algún evento comunitario que los ha hecho famosos o infames. El legado de lo que hicieron te sigue a todas partes. ¿Qué hizo tu familia? ¿Puedes sacudir la reputación? ¿Quieres?",
							"Su familia fue rica una vez, pero ahora está reducida a la pobreza. ¿Cómo perdió su fortuna? ¿Fue debido a las circunstancias o las acciones de otros? Si hay otros, ¿cómo te arruinaron y cómo les harás pagar?",
							"Su familia, antes pobre y mendigada, siempre ha luchado por sobrevivir. Sin embargo, cuando eras un muchacho, de alguna manera tu padre consiguió una gran riqueza. ¿Cómo consiguió este dinero? ¿Qué efecto tuvo en la familia? ¿Llegará alguien para reclamar o acaso acabar con la misteriosa fortuna?",
							"Atacado por un lobo cuando era niño, obtienes una cicatriz facial temible pero ahora usas su piel como un manto",
							"Mataste accidentalmente a un amigo cercano o un hermano cuando jugaban juntos. El horror de la situación le hizo huir, guardando silencio sobre la tragedia. Cuando los adultos finalmente salieron a buscar al adolescente desaparecido no se pudo encontrar ningún rastro, aunque registraron la zona donde dejaste el cuerpo. Has vivido con la culpa desde entonces, pero ¿qué fue de tu compatriota? ¿Escaparon de la muerte o le sucedió algo indescriptible al cuerpo?",
							"Recientemente experimentaste una epifanía sobrenatural que te sacudió. Mientras estaba solo, un dios vino personalmente a hablar contigo, o tal vez una multitud de espíritus se manifestaron y bailaron a tu alrededor. El evento, sea lo que sea, puede ser visto como una bendición por la comunidad local o, por el contrario, considerado una blasfemia.",
							"Sobreviviste a una terrible plaga que devastó tu comunidad. Muchos murieron y los que vivieron formaron un vínculo especial. También eres inmune a esta cepa de la plaga, algo que otros ven como un regalo de los dioses (o de Dios).",
							"Has heredado el tablero de tiro y los dados de tu tío. No hay nada extraordinario en las piezas de juego, pero siempre que las usas, siempre pareces ganar. ¿Es buena suerte, algún tipo de magia, o tu tío había encontrado una forma infalible de hacer trampa?",
							"Un pariente femenino es la criatura más hermosa en muchos, muchos kilómetros. Como ustedes dos son grandes amigos, también se convierten en el foco de atención de quienes la desean. ¿Estás celoso? ¿Estás contento? ¿Es molesta la atención? ¿Puedes hacer uso de él?",
							"Tú y un grupo de amigos formaron una banda de guerra cuando eran niños, luchando contra sajones (o celtas) imaginarios. Como adultos, han tomado caminos separados, pero están seguros de que están destinados a luchar juntos, de verdad, como hermanos (o hermanas) en armas. ¿Donde estan tus amigos ahora? ¿Cómo puedes volver a unirlos?",
							"Cerca de tu comunidad hay un anillo de piedras levantado por los dioses o los ancianos que alguna vez vivieron en toda Britania. Las piedras te fascinan y te sientes atraído por ellas constantemente. ¿Qué relación tienes con las piedras? ¿Qué significan para usted? ¿Eres el único que se siente así?",
							"Los niños mayores solían burlarse de usted de que los bosques cercanos contenían monstruos terribles: enanos, duendes, trolls, espíritus viciosos devoradores de almas y similares. Cuando creciste, comenzaste a descartar estos cuentos como historias estúpidas, es decir, hasta que varios lugareños desaparecieron mientras estaban en el bosque. Nunca fueron encontrados y ahora la gente cree que los cuentos de monstruos no son historias sino la verdad. ¿Cómo puede demostrar que están equivocados o que tienen razón? ¿Puedes encontrar a las personas desaparecidas de tu comunidad?",
							"Tu asentamiento fue atacado por sajones (o celtas) y aunque trataste de esconderte, te arrastraron pateando y gritando desde un lugar seguro y te obligaron a entretener a un grupo de guerreros borrachos que apestaban a sangre, sudor y orina. Debes haberlos entretenido bien, porque te dejan vivir. Sin embargo, nunca has olvidado el olor, el sonido de su risa o la humillación: te has comprometido a hacer que uno de esos bastardos te entretenga si alguna vez tienes la oportunidad.",
							"Un druida insistió en que se sacrificara a alguien cercano a ti para asegurar una buena cosecha después de varios años de cosechas malas y fallidas. Aunque su pariente acudió de buen grado al hombre de mimbre, no ha olvidado los gritos que le siguieron. La cosecha no fue mejor ese año. Ahora odias a todos los druidas y aborreces cualquier sacrificio humano.",
							"Los sacerdotes llegaron a su comunidad en busca de donaciones para la iglesia que estaban construyendo no muy lejos. El dinero se daba tanto para complacer a Dios como para que los sacerdotes se fueran. Sin embargo, siguen regresando y la iglesia sigue sin construirse. ¿A dónde va el dinero? ¿Cuándo se terminará la iglesia? ¿Se puede confiar en los sacerdotes?",
							"Usted nació o se ha vuelto profundamente sordo. Puede comunicarse leyendo las formas que hacen los labios de las personas y sus sentidos de la vista y el olfato se han profundizado para compensar la pérdida de audición.",
							"Acompañaste una misión comercial de tu comunidad a un lugar al otro lado de los mares. Mientras que la mayoría de la delegación pasó el viaje por mar vomitando sobre el costado del barco, usted se deleitó con el vaivén de las olas, el movimiento del mar, el rocío en su rostro y la absoluta libertad de navegar. Nunca has perdido ese amor y anhelas el mar.",
							"Tu abuelo y tu padre siempre han estado obsesionados con todo lo romano. Los romanos fueron grandes inventores, constructores, soldados y gobernadores, y lo que hicieron por Britania nunca puede ser descartado ni olvidado. Aunque eran invasores, hicieron cumplir la paz y muchos británicos optaron por convertirse en romanos, al igual que algunos celtas optaron por convertirse en sajones y viceversa. Has crecido con un aprecio y una admiración por todas las cosas romanas y búscalas cuando puedas. Te gusta vestirte a la romana y esperas, algún día, visitar Roma o Constantinopla.",
							"Para unir clanes o tribus enfrentadas, se ha decidido que te casarás con la hija / hijo del enemigo. Se conoció por primera vez en la ceremonia de compromiso y, para su asombro, descubrió que realmente le agradaba su futura esposa / esposo. Lamentablemente, las relaciones se rompieron gravemente y la alianza prevista no se llevará a cabo, pero te has enamorado. Tus lealtades se debaten entre tu gente y la persona que amas. ¿Qué vas a hacer? ¿A quién elegirás?",
							"Su comunidad fue afligida por la pestilencia. Los sacerdotes cristianos dijeron que era porque Dios estaba enojado porque había tantos pecadores en la comunidad y tenían que ser expulsados. Curiosamente, todos estos pecadores eran paganos y fueron acosados ​​de sus hogares, sus posesiones robadas y las ropas arrancadas de sus espaldas. ¿Participaste? ¿Eras uno de los fugitivos? ¿Tenía razón el sacerdote? ¿Se levantó la pestilencia?",
							"Un pariente muy cercano o un amigo de la infancia lo traiciona, lo que lleva a la pérdida de reputación, al castigo y a la vergüenza para usted y su familia. ¿Por qué hizo esto su familiar o amigo? ¿Formaba parte de un plan más amplio? No puedes librarte de la necesidad de venganza y por eso esta persona es ahora tu Enemigo.",
							"Tiene un sueño recurrente sobre un hito destacado (un río, una colina, un desfiladero, un bosque o similar). En el sueño, eres el señor del área donde se encuentra este hito y estás muy orgulloso de tus territorios. Sabes que este es tu destino: debes encontrar este lugar, visitarlo y diseñar tu vida para que tu destino sea manifiesto.",
							"Descubriste un cachorro de animal o un huevo de ave y lo criaste a mano; obtienes un animal salvaje o ave de presa completamente desarrollado como mascota leal, pero debes alimentar y controlar a la criatura.",
							"Eres polidactilo: un dedo extra en una o ambas manos. No obtienes ningún beneficio especial de esta característica curiosa, pero ciertamente asegura que se hable de ti. Los paganos lo ven como una marca favorable de los dioses; los cristianos lo ven como una marca del diablo. Lo ve como una maldita molestia porque es difícil conseguir guantes que le queden bien.",
							"Tienes ojos de colores bastante diferentes. Esto puede ser el resultado de un accidente infantil, una enfermedad o simplemente un capricho de la naturaleza. Te hace fácil de identificar, pero también es visto como una señal de sospecha tanto por paganos como por cristianos. Los paganos piensan que puedes ver el mundo de los espíritus con uno de tus ojos, mientras que los cristianos creen que es la marca de Caín.",
							"Tiene un estómago y un paladar inusualmente fuertes para los alimentos que a otros les repugnan. El olor y el sabor no te molestan, y las texturas inusuales te parecen interesantes. Usted no es inmune a los posibles efectos de comer alimentos o bebidas enfermos, pero la vista, el olfato y el gusto no lo desaniman para probarlos.",
							"Un alimento en particular es simplemente desagradable para usted. El más mínimo olor o sabor te provoca arcadas o náuseas: queso, huevos, cerveza, tocino, caza; no te enferma per se, pero simplemente no lo tolera.",
							"Su padre afirma que su familia desciende de la línea original de reyes que fundaron la tierra: si alguna vez hubo un derecho a la Gran Realeza, ¡es su familia! La prueba de esta afirmación se perdió hace mucho tiempo, destruida por los usurpadores enemigos que pusieron a su familia en su curso actual. Deberías reclamar tu derecho de nacimiento. Encuentre la prueba necesaria para demostrar que usted y su familia son los gobernantes legítimos.",
							"Una bolsa de huesos viejos ha estado en su familia durante generaciones. Se afirma que los huesos pertenecen a un gran héroe o santo de su religión. Como tales, los huesos son reliquias sagradas y siempre deben tratarse con reverencia. De vez en cuando, tu abuela ponía los huesos en una línea y cantaba oraciones sobre ellos. Siempre pensaste que era un poco extraña. Luego, hace unos años, un druida o sacerdotes llegaron a tu casa y exigieron ver la bolsa de huesos. Tu abuela los trajo y el santo miró dentro de la bolsa. Dejó escapar un grito de terror, dejó caer la bolsa y huyó de su casa. Cuando miraste allí, los huesos parecían bastante normales. Ahora la bolsa está en tu poder. ¿Qué hizo que el druida o el sacerdote huyeran? ¿Qué significan los huesos? ¿A quién pertenecían?",
							"Un viajero pobre llegó a su aldea en busca de ayuda y refugio. Lo alimentaste, lo vististe y cuidaste sus heridas. Afirmó ser solo un vagabundo humilde al que habían robado en el camino. Al día siguiente, se había ido, llevándose toda la riqueza de su familia. Recientemente asistió a una fiesta con mucha gente rica e importante. Allí, en la mesa alta, riendo y bromeando, estaba el 'pobre' viajero que te robó. No hizo nada en ese momento porque no podía estar completamente seguro, pero ahora está seguro de que es el mismo hombre. ¿Qué vas a hacer? ¿Cómo conseguirás justicia para tu familia? ¿Alguien te creerá?",
							"Cuando eras niño, tenías un grupo de amigos cercanos. Jugando juntos cerca de unas antiguas ruinas romanas, encontraron un pozo escondido que contenía una bolsa de dinero y joyas: plata, oro y piedras preciosas. Aceptaste mantener tu tesoro en secreto y, cuando seas mayor, regresar juntos y dividirlo entre ustedes por igual. Escondiste bien el tesoro, de modo que solo ustedes cuatro pudieran encontrarlo. Llegó el día y fuiste a recuperar tu botín y descubriste que el tesoro se había ido. Estaba bien escondido y solo ustedes cuatro podían saberlo. ¿Alguno de ustedes le dijo a alguien más? ¿Alguno de ustedes ha tomado el dinero y está fingiendo inocencia? ¿Fuiste observado? Ahora todos sospechan y están resentidos el uno con el otro. Quieres descubrir la verdad. Más concretamente, quieres el dinero.",
							"Los miembros de su clan son comerciantes. Hiciste un largo viaje con ellos al norte (o al sur) del Gran Muro construida por los romanos. Pasaste varios meses entre esta gente extraña, aprendiendo sus costumbres y observando sus extraños caminos. Ahora sientes cierto parentesco con ellos, a pesar de las diferencias entre tus tribus y formas de vida.",
							"Después de un concurso de bebidas especialmente espectacular, te despertaste para descubrir que no solo tenías la resaca del infierno, sino que también te habías hecho un peculiar tatuaje en forma de remolino en el hombro y la parte superior del brazo. No recuerdas haberlo hecho, y parece que debería haber tardado muchas horas en hacerlo. Tus compañeros estaban igual de borrachos y ninguno de ellos recuerda cómo te hiciste el tatuaje, ninguno tiene uno. A pesar de no saber de dónde viene, te gusta. Es diferente, muy diferente a los tatuajes de tu tribu. También sospechas que, algún día, descubrirás cómo lo conseguiste.",
							"Sobreviviste a un incendio que destruyó parte de tu asentamiento. Tira 1d20 dos veces para descubrir qué ubicaciones de impacto quedaron gravemente marcadas por las llamas. Ahora está aterrorizado por los grandes incendios: cualquier cosa más grande que un campamento o un fuego para cocinar hace que se retire a una distancia muy segura, sin importar el frío que haga.",
							"Cuando era niño, casi se ahoga cuando se cae a un río que fluye rápidamente. El agua es ahora un lugar aterrador para ti: solo puedes cruzar un río a través de un puente resistente o un vado muy poco profundo. El mar abierto es demasiado aterrador para contemplarlo.",
							"Atentado por otros niños, subiste al árbol más alto del bosque local y casi llegaste a la cima cuando perdiste el equilibrio y te caíste. Te rompiste varios huesos en la caída y, aunque te recuperaste por completo, ahora estás aterrorizado por las alturas. Escalar cualquier altura superior a 10 pies requiere que hagas una tirada de Fuerza de Voluntad para continuar y, si puedes evitar una escalada, lo harás.",
							"Le aterrorizan los espacios reducidos. Las casas y las chozas están bien, pero cualquier cosa que restrinja tu movimiento te aterroriza y requiere una tirada de Fuerza de Voluntad para que puedas siquiera contemplar entrar. Si se ve obligado a entrar en un espacio confinado, debe tener éxito en una tirada de Fuerza de voluntad dura para evitar quedar paralizado por el miedo.",
							"Tu cabello se está volviendo prematuramente gris, lo que te hace parecer unos 10 años mayor de lo que eres, pero también bastante distinguido y maduro. Has intentado teñir tu cabello con una variedad de tintes a base de hierbas, pero demasiado pronto las canas vuelven a aparecer. ¿Sigues intentando esconderlo, o abrazar la melena plateada?",
							"En una expedición de caza, de alguna manera te separaste del grupo principal y te perdiste en el bosque. Llegaste a un valle aislado donde una hermosa mujer, con cabello dorado y túnica blanca, estaba esperando. Sabía tu nombre, sabía que estabas perdido y te pidió que te quedaras a hablar con ella. No recuerdas de qué hablaste, pero cuando te diste cuenta de que estaba oscureciendo dijiste que tenías que ir. Ella sonrió, te besó en la frente y te dijo cómo encontrar el camino para regresar a tu asentamiento. Cuando llegaste a casa te encontraste con que había pasado una semana entera: tu familia había pensado que te mataban o te tomaban como esclavo. Cuando les hablaste de la Mujer de los cabellos dorados, nunca volvieron a mencionar tu ausencia. Sientes que hay más en todo esto. ¿Qué podría significar?",
							"Hiciste un descubrimiento importante que necesitaba ser informado a tu señor. Era necesario que confiaras en alguien más para poder llamar la atención del señor, pero el confidente fue a tus espaldas y reclamó el crédito por lo que habías descubierto (y fue recompensado en consecuencia). Te sientes engañado e impulsado a exponer la traición que has sufrido. ¿Cómo lo harás?",
							"De niño fuiste esclavizado por los sajones (o por los celtas, si era sajón). Te marcaron en la mejilla izquierda con una de las extrañas runas angulares del sajón que indicaba que eras propiedad de alguien. ¿Cómo escapaste de la esclavitud? ¿Alguien te salvó? Sin embargo, la cicatriz sigue ahí como recordatorio. Puedes intentar disfrazarlo con pinturas faciales como el gofre o un tatuaje que lo cubra, pero ya sabes, de primera mano, lo que es ser esclavo.",
							"O te legaron, o te encontraron, una piel de ciervo raspada que ha sido pintada con un contorno de Britania. Muestra claramente el Gran Muro, los grandes ríos y las colinas. También tiene una serie de marcas deliberadas hechas en todo el mapa, trece en total, que se encuentran tanto al norte como al sur de el Gran Muro. ¿Qué significan estas marcas? ¿Son las ubicaciones de los trece tesoros de Britania? ¿Quizás marcan ciudades romanas? Quizás se refieran a otra cosa. El mapa te fascina y tienes la intención de descubrir qué representa.",
							"Cerca de su aldea hay un túmulo funerario largo y con jorobas. Ha estado sellado durante siglos y todos dicen que contiene los restos de un caudillo de los ancianos. Como un desafío, te aventuraste en él, apretándote entre las piedras derrumbadas de la entrada bloqueada. Dentro hacía frío y húmedo. No encontraste ningún cuerpo, pero sí encontraste una piedra extraña, del tamaño del puño de un hombre, tallada con muchas marcas y sellos extraños. Lo sacaste del túmulo y lo escondiste. Una semana después, un lobo mató a la mayoría de las ovejas del pueblo. Un mes después, todos los pollos fueron asesinados por zorros. Un año después, todas las vacas enfermaron de fiebre y murieron. Nunca devolvió la piedra, algo se lo impide. ¿Qué morirá después ?.",
							"Su padre era un hombre jactancioso que afirmaba que, cuando llegara a la edad adulta, lograría algo muy especial, algo que nadie más había logrado. ¿Qué prometió? ¿Podrás cumplir con sus jactancias? ¿Quieres? ¿Por qué se jactó en primer lugar?",
							"Uno de tus parientes mató a un druida: esto significa que tu familia ahora está maldita por los dioses (incluso si eres cristiano y no los adoras). ¿Qué forma toma la maldición? ¿Cómo te afecta? ¿Qué debes hacer para levantarlo?",
							"Tu hermano era alguien a quien amabas mucho y te llevabas muy bien. Fue enviado a un clan distante. Cuando regresó, había cambiado más allá de lo imaginable: el amable y cariñoso hermano se había convertido en un grosero cruel, sarcástico y arrogante. Lo amas todavía, pero odias en lo que se ha convertido. ¿A quién culpar? ¿El clan o tu hermano? ¿Cómo afecta esto a su relación? Parece detestarte y despreciarte.",
							"De niño fuiste elegido para ser el centro de un gran e intenso ritual religioso. La experiencia tuvo un efecto profundo en ti, y ahora no tienes ninguna duda de que los dioses (o Dios) existen, dan forma a todo en este mundo y tienen un destino para todos. Especialmente tienes un destino que cumplir. ¿Qué te fue revelado durante ese ritual? ¿Cómo guía ahora tu vida?",
							"Justo antes de que te convirtieras en adulto, fuiste seducido por la esposa del caudillo. Lo hizo en secreto y lo que te mostró y lo que experimentaste fue tan placentero que no puedes sacarla de tu mente, aunque no puedes ni debes pensar en ella de esa manera. En su mayoría, te ignora en estos días, pero de vez en cuando te ofrece una sonrisa maliciosa y te llenas de lujuria. ¿Qué vas a hacer? ¿Puedes controlar tus impulsos?",
							"Asesinaste a alguien. ¿Por qué? ¿Fue venganza? ¿Autodefensa? ¿A quién mataste? ¿Era un extraño o alguien que conocías? Has escondido el cuerpo y, hasta ahora, nunca se ha descubierto, pero vives con el temor de que alguien lo encuentre y empiece a hacer preguntas. Si hacen las preguntas correctas, entonces las pistas podrían apuntar a ti." ];
	}
		
	get trasfondos() 
	{
		return this._trasfondos.clone().shuffle();
	}
	
	trasfondo() {
		var numero = Comun.random(this._trasfondos.length,0);
		var aTrasfondos = [];
		if ( numero == this._trasfondos.length ) {
			var randomtrasfondos = this.trasfondos;
			aTrasfondos.push(randomtrasfondos[0]);
			aTrasfondos.push(randomtrasfondos[1]);
		}
		else {
			aTrasfondos.push(this._trasfondos[numero]);
		}
		return aTrasfondos;
	}
}

let trasfondos = new Trasfondos();
